# Generated by Django 5.2.3 on 2025-07-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bass_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_diagnostico', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
