# Generated by Django 5.2.3 on 2025-07-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bass_app', '0002_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('unidad_referencia_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
