# Generated by Django 5.2.3 on 2025-07-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bass_app', '0003_medicofuncionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sintomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puntacion', models.IntegerField(default=0)),
            ],
        ),
    ]
