# Generated by Django 5.2.3 on 2025-07-23 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bass_app', '0004_sintomas'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('puntaje_total', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('pendiente', 'Pendiente'), ('completado', 'Completado')], default='activo', max_length=50)),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bass_app.paciente')),
            ],
        ),
    ]
